steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/zeya-telegram-bot:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/zeya-telegram-bot:$TAG_NAME', 'gcr.io/$PROJECT_ID/zeya-telegram-bot:latest']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', '--region', 'europe-north1 ', '--image', 'gcr.io/$PROJECT_ID/zeya-telegram-bot', '--platform', 'managed', 'zeya-telegram-bot' ]
images:
  - 'gcr.io/$PROJECT_ID/zeya-telegram-bot'